import type { MigrationConfig, MigrationJob, TableInfo } from '../../types';
const base = import.meta.env.VITE_API_URL || `http://${window.location.hostname}:8009/api`; const mock = (import.meta.env.VITE_API_MODE ?? 'real') === 'mock';
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
const mockJobs = new Map<string, MigrationJob>();
async function responseError(response: Response, fallback: string): Promise<never> {
  let message = fallback;
  try {
    const data = await response.json();
    message = data?.detail?.message ?? data?.detail ?? data?.error?.message ?? message;
  } catch { /* Keep the fallback when the server did not return JSON. */ }
  throw new Error(typeof message === 'string' ? message : fallback);
}
export async function testConnection(input: unknown): Promise<{success:boolean; database:string; latency_ms:number; server_version?:string; connection_token?:string}> { if (mock) { await wait(450); return { success: true, database: (input as {database:string}).database, latency_ms: 0, connection_token: 'mock' }; } const value = input as {database_type:string}; const r = await fetch(`${base}/connections/${value.database_type === 'sqlserver' ? 'source':'destination'}/test`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}); const data = await r.json(); if (!r.ok || data.success === false) throw new Error(data?.error?.message ?? 'Connection test failed'); return data; }
export async function getSchemas(token: string): Promise<string[]> { if (mock) return ['dbo']; const response = await fetch(`${base}/source/schemas`, { headers: { 'X-Connection-Token': token } }); if (!response.ok) throw new Error('Unable to load SQL Server schemas'); return (await response.json()).schemas; }
export async function getTables(schema: string, token: string): Promise<TableInfo[]> { if (mock) { await wait(300); return [{ name: 'customers', estimated_rows: 120, size_mb: 1 }, { name: 'orders', estimated_rows: 480, size_mb: 3 }]; } const response = await fetch(`${base}/source/tables?schema=${encodeURIComponent(schema)}`, { headers: { 'X-Connection-Token': token } }); if (!response.ok) throw new Error('Unable to load tables from the selected schema'); return (await response.json()).tables; }
export async function preflight(config: MigrationConfig) { if (mock) { await wait(500); return {ready:true,checks:['Source connection','Destination connection','Selected tables','pgloader'].map(name=>({name,status:'passed'}))}; } const response = await fetch(`${base}/migrations/preflight`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)}); if (!response.ok) return responseError(response, 'Preflight checks failed'); return response.json(); }
export async function createMigration(config: MigrationConfig): Promise<MigrationJob> { if (mock) { await wait(500); const job = {id:`mig_${Date.now()}`,status:'QUEUED' as const,source_database:config.source.database,destination_database:config.destination.database,selected_schema:config.schema,selected_tables:config.tables,tables_processed:0,error_count:0}; mockJobs.set(job.id, job); return job; } const response = await fetch(`${base}/migrations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)}); if (!response.ok) return responseError(response, 'Unable to start migration'); return response.json(); }
export async function getMigration(id: string): Promise<MigrationJob> { if (mock) { const job = mockJobs.get(id); if (!job) throw new Error('Migration not found'); return {...job, status:'COMPLETED', tables_processed:job.selected_tables.length, completed_at:new Date().toISOString()}; } const response = await fetch(`${base}/migrations/${id}`); if (!response.ok) throw new Error('Unable to load migration status'); return response.json(); }
export async function getLogs(id: string): Promise<Array<{timestamp:string; level:string; component:string; message:string}>> { if (mock) return [{timestamp:new Date().toISOString(), level:'INFO', component:'COMPLETED', message:'Mock migration completed successfully.'}]; const response = await fetch(`${base}/migrations/${id}/logs`); if (!response.ok) throw new Error('Unable to load migration logs'); return (await response.json()).logs; }
export async function cancelMigration(id: string): Promise<MigrationJob> { const response = await fetch(`${base}/migrations/${id}/cancel`, { method: 'POST' }); if (!response.ok) throw new Error('Unable to cancel migration'); return response.json(); }
export function subscribeToMigrationEvents(id: string, onEvent: () => void): () => void { const stream = new EventSource(`${base}/migrations/${id}/events`); stream.onmessage = onEvent; stream.onerror = () => stream.close(); return () => stream.close(); }
